# Generated by Django 5.2.9 on 2025-12-26 14:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название точки', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание точки', null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Географическая координата (широта, долгота)', srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(help_text='Пользователь, создавший точку', on_delete=django.db.models.deletion.CASCADE, related_name='owned_geopoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гео-точка',
                'verbose_name_plural': 'Гео-точки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(help_text='Пользователь, написавший сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(help_text='Точка, к которой привязано сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='points_app.geopoint')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
